<?php
	 header('Access-Control-Allow-Origin: *');
   

include 'connect.php';
// $opdno = $_GET["opdno"];




$data=array();

$strSQL  = "SELECT
CASE WHEN TO_CHAR(CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN TO_CHAR(CURRENT_DATE, 'yyyy')+542 ELSE TO_CHAR(CURRENT_DATE, 'yyyy') +543 END as  YEARS,
ROUND ((  IPDDEATH.IPDDISCHARGE / x.ipddischarge) * 1000,2) as dataperson
FROM
(
	SELECT
		'1' AS YEAR,
		COUNT (IPDTRANS.AN) AS ipddischarge
	FROM
		IPDTRANS
	INNER JOIN DISEASE_WAREHOUSE on IPDTRANS.RUN_AN = DISEASE_WAREHOUSE.IPD_RUN_AN AND IPDTRANS.YEAR_AN = DISEASE_WAREHOUSE.IPD_YEAR_AN
	WHERE
		IPDTRANS.DATEDISCH >= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') || '/' || '10/01',
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') - 1 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	END
	AND IPDTRANS.DATEDISCH <= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') + 1 || '/' || TO_CHAR (CURRENT_DATE, 'mm') || '/' || TO_CHAR (CURRENT_DATE, 'dd') ,
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') || '/' || TO_CHAR (CURRENT_DATE, 'mm') || '/' || TO_CHAR (CURRENT_DATE, 'dd') ,
			'yyyy/mm/dd'
		)
	END
	and DISEASE_WAREHOUSE.OPDIPD = 'I'
	AND (DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z380' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z383' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z386' )
) x
INNER JOIN (
SELECT
	'1' AS YEAR,
	COUNT (IPDTRANS.AN) AS ipddischarge
FROM
	IPDTRANS
	INNER JOIN DISEASE_WAREHOUSE on IPDTRANS.RUN_AN = DISEASE_WAREHOUSE.IPD_RUN_AN AND IPDTRANS.YEAR_AN = DISEASE_WAREHOUSE.IPD_YEAR_AN
INNER JOIN PATIENTS ON DISEASE_WAREHOUSE.HN = PATIENTS.HN
WHERE
	IPDTRANS.DATEDISCH >= CASE
WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
	TO_DATE (
		TO_CHAR (CURRENT_DATE, 'yyyy') || '/' || '10/01',
		'yyyy/mm/dd'
	)
ELSE
	TO_DATE (
		TO_CHAR (CURRENT_DATE, 'yyyy') - 1 || '/' || '10/01',
		'yyyy/mm/dd'
	)
END
AND IPDTRANS.DATEDISCH <= CASE
WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
	TO_DATE (
		TO_CHAR (CURRENT_DATE, 'yyyy') + 1 || '/' || TO_CHAR (CURRENT_DATE, 'mm') || '/' || TO_CHAR (CURRENT_DATE, 'dd') ,
			'yyyy/mm/dd'
		)
ELSE
	TO_DATE (
		TO_CHAR (CURRENT_DATE, 'yyyy') || '/' || TO_CHAR (CURRENT_DATE, 'mm') || '/' || TO_CHAR (CURRENT_DATE, 'dd') ,
			'yyyy/mm/dd'
		)
END
and IPDTRANS.DS_STATUS_ID = '9'
	and DISEASE_WAREHOUSE.OPDIPD = 'I'
	AND (DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z380' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z383' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z386' )
and trunc(PATIENTS.BIRTHDAY-add_months(IPDTRANS.DATEDISCH,trunc(months_between(PATIENTS.BIRTHDAY,IPDTRANS.DATEDISCH)/12)*12+trunc(mod(months_between(PATIENTS.BIRTHDAY,IPDTRANS.DATEDISCH),12)))) <= 28

) ipddeath ON x. YEAR = IPDDEATH. YEAR

UNION 
SELECT
CASE WHEN TO_CHAR(CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN TO_CHAR(CURRENT_DATE, 'yyyy')+541 ELSE TO_CHAR(CURRENT_DATE, 'yyyy') +542 END as  YEARS,
ROUND ((  IPDDEATH.IPDDISCHARGE / x.ipddischarge) * 1000,2) as dataperson



FROM
(
	
	SELECT
		'1' AS YEAR,
		COUNT (IPDTRANS.AN) AS ipddischarge
	FROM
		IPDTRANS
	INNER JOIN DISEASE_WAREHOUSE on IPDTRANS.RUN_AN = DISEASE_WAREHOUSE.IPD_RUN_AN AND IPDTRANS.YEAR_AN = DISEASE_WAREHOUSE.IPD_YEAR_AN
	WHERE
		IPDTRANS.DATEDISCH >= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')-1 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') - 2 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	END
AND IPDTRANS.DATEDISCH <= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')  || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -1 || '/' ||'09/30' ,
			'yyyy/mm/dd'
		)
	END
	and DISEASE_WAREHOUSE.OPDIPD = 'I'
	AND (DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z380' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z383' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z386' )
) x
INNER JOIN (
SELECT
	'1' AS YEAR,
	COUNT (IPDTRANS.AN) AS ipddischarge
FROM
	IPDTRANS
	INNER JOIN DISEASE_WAREHOUSE on IPDTRANS.RUN_AN = DISEASE_WAREHOUSE.IPD_RUN_AN AND IPDTRANS.YEAR_AN = DISEASE_WAREHOUSE.IPD_YEAR_AN
INNER JOIN PATIENTS ON DISEASE_WAREHOUSE.HN = PATIENTS.HN
	WHERE
		IPDTRANS.DATEDISCH >= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -1 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') - 2 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	END
	AND IPDTRANS.DATEDISCH <= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')  || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -1 || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	END
and IPDTRANS.DS_STATUS_ID = '9'
	and DISEASE_WAREHOUSE.OPDIPD = 'I'
	AND (DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z380' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z383' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z386' )
and trunc(PATIENTS.BIRTHDAY-add_months(IPDTRANS.DATEDISCH,trunc(months_between(PATIENTS.BIRTHDAY,IPDTRANS.DATEDISCH)/12)*12+trunc(mod(months_between(PATIENTS.BIRTHDAY,IPDTRANS.DATEDISCH),12)))) <= 28

) ipddeath ON x. YEAR = IPDDEATH. YEAR

union 
SELECT
CASE WHEN TO_CHAR(CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN TO_CHAR(CURRENT_DATE, 'yyyy')+540 ELSE TO_CHAR(CURRENT_DATE, 'yyyy') +541 END as  YEARS,
ROUND ((  IPDDEATH.IPDDISCHARGE / x.ipddischarge) * 1000,2) as dataperson



FROM
(
	
	SELECT
		'1' AS YEAR,
		COUNT (IPDTRANS.AN) AS ipddischarge
	FROM
		IPDTRANS
	INNER JOIN DISEASE_WAREHOUSE on IPDTRANS.RUN_AN = DISEASE_WAREHOUSE.IPD_RUN_AN AND IPDTRANS.YEAR_AN = DISEASE_WAREHOUSE.IPD_YEAR_AN
	WHERE
		IPDTRANS.DATEDISCH >= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')-2 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') - 3 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	END
AND IPDTRANS.DATEDISCH <= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')-1  || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -2 || '/' ||'09/30' ,
			'yyyy/mm/dd'
		)
	END
	and DISEASE_WAREHOUSE.OPDIPD = 'I'
	AND (DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z380' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z383' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z386' )
) x
INNER JOIN (
SELECT
	'1' AS YEAR,
	COUNT (IPDTRANS.AN) AS ipddischarge
FROM
	IPDTRANS
	INNER JOIN DISEASE_WAREHOUSE on IPDTRANS.RUN_AN = DISEASE_WAREHOUSE.IPD_RUN_AN AND IPDTRANS.YEAR_AN = DISEASE_WAREHOUSE.IPD_YEAR_AN
INNER JOIN PATIENTS ON DISEASE_WAREHOUSE.HN = PATIENTS.HN
	WHERE
		IPDTRANS.DATEDISCH >= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -2 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') - 3 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	END
	AND IPDTRANS.DATEDISCH <= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')-1  || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -2 || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	END
and IPDTRANS.DS_STATUS_ID = '9'
	and DISEASE_WAREHOUSE.OPDIPD = 'I'
	AND (DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z380' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z383' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z386' )
and trunc(PATIENTS.BIRTHDAY-add_months(IPDTRANS.DATEDISCH,trunc(months_between(PATIENTS.BIRTHDAY,IPDTRANS.DATEDISCH)/12)*12+trunc(mod(months_between(PATIENTS.BIRTHDAY,IPDTRANS.DATEDISCH),12)))) <= 28

) ipddeath ON x. YEAR = IPDDEATH. YEAR

UNION 

SELECT
CASE WHEN TO_CHAR(CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN TO_CHAR(CURRENT_DATE, 'yyyy')+539 ELSE TO_CHAR(CURRENT_DATE, 'yyyy') +540 END as  YEARS,
ROUND ((  IPDDEATH.IPDDISCHARGE / x.ipddischarge) * 1000,2) as dataperson



FROM
(
	
	SELECT
		'1' AS YEAR,
		COUNT (IPDTRANS.AN) AS ipddischarge
	FROM
		IPDTRANS
	INNER JOIN DISEASE_WAREHOUSE on IPDTRANS.RUN_AN = DISEASE_WAREHOUSE.IPD_RUN_AN AND IPDTRANS.YEAR_AN = DISEASE_WAREHOUSE.IPD_YEAR_AN
	WHERE
		IPDTRANS.DATEDISCH >= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')-3 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') - 4 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	END
AND IPDTRANS.DATEDISCH <= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')-2 || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -3 || '/' ||'09/30' ,
			'yyyy/mm/dd'
		)
	END
	and DISEASE_WAREHOUSE.OPDIPD = 'I'
	AND (DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z380' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z383' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z386' )
) x
INNER JOIN (
SELECT
	'1' AS YEAR,
	COUNT (IPDTRANS.AN) AS ipddischarge
FROM
	IPDTRANS
	INNER JOIN DISEASE_WAREHOUSE on IPDTRANS.RUN_AN = DISEASE_WAREHOUSE.IPD_RUN_AN AND IPDTRANS.YEAR_AN = DISEASE_WAREHOUSE.IPD_YEAR_AN
INNER JOIN PATIENTS ON DISEASE_WAREHOUSE.HN = PATIENTS.HN
	WHERE
		IPDTRANS.DATEDISCH >= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -3 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') - 4 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	END
	AND IPDTRANS.DATEDISCH <= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')-2  || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -3 || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	END
and IPDTRANS.DS_STATUS_ID = '9'
	and DISEASE_WAREHOUSE.OPDIPD = 'I'
	AND (DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z380' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z383' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z386' )
and trunc(PATIENTS.BIRTHDAY-add_months(IPDTRANS.DATEDISCH,trunc(months_between(PATIENTS.BIRTHDAY,IPDTRANS.DATEDISCH)/12)*12+trunc(mod(months_between(PATIENTS.BIRTHDAY,IPDTRANS.DATEDISCH),12)))) <= 28

) ipddeath ON x. YEAR = IPDDEATH. YEAR
UNION
SELECT
CASE WHEN TO_CHAR(CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN TO_CHAR(CURRENT_DATE, 'yyyy')+538 ELSE TO_CHAR(CURRENT_DATE, 'yyyy') +539 END as  YEARS,
ROUND ((  IPDDEATH.IPDDISCHARGE / x.ipddischarge) * 1000,2) as dataperson



FROM
(
	
	SELECT
		'1' AS YEAR,
		COUNT (IPDTRANS.AN) AS ipddischarge
	FROM
		IPDTRANS
	INNER JOIN DISEASE_WAREHOUSE on IPDTRANS.RUN_AN = DISEASE_WAREHOUSE.IPD_RUN_AN AND IPDTRANS.YEAR_AN = DISEASE_WAREHOUSE.IPD_YEAR_AN
	WHERE
		IPDTRANS.DATEDISCH >= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')-4 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') - 5 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	END
AND IPDTRANS.DATEDISCH <= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')-3 || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -4 || '/' ||'09/30' ,
			'yyyy/mm/dd'
		)
	END
	and DISEASE_WAREHOUSE.OPDIPD = 'I'
	AND (DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z380' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z383' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z386' )
) x
INNER JOIN (
SELECT
	'1' AS YEAR,
	COUNT (IPDTRANS.AN) AS ipddischarge
FROM
	IPDTRANS
	INNER JOIN DISEASE_WAREHOUSE on IPDTRANS.RUN_AN = DISEASE_WAREHOUSE.IPD_RUN_AN AND IPDTRANS.YEAR_AN = DISEASE_WAREHOUSE.IPD_YEAR_AN
INNER JOIN PATIENTS ON DISEASE_WAREHOUSE.HN = PATIENTS.HN
	WHERE
		IPDTRANS.DATEDISCH >= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -4 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') - 5 || '/' || '10/01',
			'yyyy/mm/dd'
		)
	END
	AND IPDTRANS.DATEDISCH <= CASE
	WHEN TO_CHAR (CURRENT_DATE, 'mm') IN ('10', '11', '12') THEN
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy')-3  || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	ELSE
		TO_DATE (
			TO_CHAR (CURRENT_DATE, 'yyyy') -4 || '/' || '09/30' ,
			'yyyy/mm/dd'
		)
	END
	and DISEASE_WAREHOUSE.OPDIPD = 'I'
	AND (DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z380' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z383' OR DISEASE_WAREHOUSE.ICD_CODE LIKE 'Z386' )
and trunc(PATIENTS.BIRTHDAY-add_months(IPDTRANS.DATEDISCH,trunc(months_between(PATIENTS.BIRTHDAY,IPDTRANS.DATEDISCH)/12)*12+trunc(mod(months_between(PATIENTS.BIRTHDAY,IPDTRANS.DATEDISCH),12)))) <= 28

and IPDTRANS.DS_STATUS_ID = '9'
) ipddeath ON x. YEAR = IPDDEATH. YEAR




";


$objParse = oci_parse ($objConnect, $strSQL);
oci_execute($objParse,OCI_DEFAULT);
while($rs_pmk=oci_fetch_array($objParse,OCI_BOTH)){

	$a['YEARS']=$rs_pmk[0];
	$a['DATA']=$rs_pmk[1];

	


	array_push($data,$a);
}	
	
// $data_array2 = array("data" => $data);

echo json_encode($data);

oci_close($objConnect);





?>
